"""Shadow-only Mathematical Intelligence Engine contracts and features.

Gates 1 and 2 deliberately expose no decision or execution adapter.
"""

from app.mie.adapters import adapt_legacy_mathematical_core
from app.mie.contracts import (
    CalibrationStatus,
    DecisionAction,
    DecisionCandidate,
    DecisionChecks,
    Evidence,
    EvidenceDirection,
    EvidenceUse,
    ForecastHorizon,
    MarketRegime,
    MieShadowTrace,
    ModelHealth,
    ModelHealthStatus,
    ProbabilityForecast,
    ProbabilityVector,
    RegimeProbabilityVector,
    RegimeSnapshot,
    ValidationLevel,
    ValidationMetric,
    ValidationReference,
)
from app.mie.features import (
    DynamicsFeatures,
    FeatureBar,
    FeatureWindow,
    GeometryFeatures,
    MathematicalFeatureSnapshot,
    MomentumFeatures,
    SignalFeatures,
    StatisticsFeatures,
    SwingPoint,
    causal_dynamics,
    causal_signal_features,
    confirmed_geometry_features,
    mathematical_feature_snapshot,
    momentum_features,
    statistical_features,
)

__all__ = [
    "CalibrationStatus",
    "DecisionAction",
    "DecisionCandidate",
    "DecisionChecks",
    "Evidence",
    "EvidenceDirection",
    "EvidenceUse",
    "DynamicsFeatures",
    "FeatureBar",
    "FeatureWindow",
    "ForecastHorizon",
    "GeometryFeatures",
    "MathematicalFeatureSnapshot",
    "MarketRegime",
    "MieShadowTrace",
    "ModelHealth",
    "ModelHealthStatus",
    "MomentumFeatures",
    "ProbabilityForecast",
    "ProbabilityVector",
    "RegimeProbabilityVector",
    "RegimeSnapshot",
    "SignalFeatures",
    "StatisticsFeatures",
    "SwingPoint",
    "ValidationLevel",
    "ValidationMetric",
    "ValidationReference",
    "adapt_legacy_mathematical_core",
    "causal_dynamics",
    "causal_signal_features",
    "confirmed_geometry_features",
    "mathematical_feature_snapshot",
    "momentum_features",
    "statistical_features",
]
